### ISSUE TITLE
ReservedConcurrentExecutions property not recognized

### ISSUE THREAD

**Issue by chapmanjonPFG** [stelligent/cfn-model#88]
With I run `cfn_nag_scan` on a template with a resource such as this,

```
ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example_function.handler
      CodeUri: ../src
      Role: !GetAtt ExampleRole.Arn
      Runtime: python3.8
      ReservedConcurrentExecutions: 1
```

I get warned with `W92` that `ReservedConcurrentExecutions` should be defined.
So it appears that the property is not being recognized.

I opened an issue on cfn_nag: https://github.com/stelligent/cfn_nag/issues/547
But it sounds like that the issue could potentially be in cfn-model
